LPD-34627 publication timeline popup api adjustments
liferay-site-management/liferay-portal pull request #1372
Opened 2024-09-04 20:25 UTC by ctang3

This is branched from https://github.com/liferay-site-management/liferay-portal/pull/1346 and depends on that getting merged first. The changes for this PR are ready for review and should change little, if any, in response to any changes in https://github.com/liferay-site-management/liferay-portal/pull/1346.

https://liferay.atlassian.net/browse/LPD-34627

2024-09-05 00:39 UTC, ctang3 commented
@pei-jung This is ready for review, but pending on fixing the new test from https://github.com/liferay-site-management/liferay-portal/pull/1346

More context for the https://github.com/liferay-site-management/liferay-portal/pull/1372/commits/e608cce993b5b8c786765bf3d55f1c7782822b0b change:

- https://stackoverflow.com/questions/54954385/react-useeffect-causing-cant-perform-a-react-state-update-on-an-unmounted-comp
- https://stackoverflow.com/questions/73114731/multiple-fetch-in-useeffect-fetch-data-depend-on-another-fetch-data

2024-09-05 22:42 UTC, pei-jung requested changes

2024-09-05 22:42 UTC, pei-jung commented on modules/apps/change-tracking/change-tracking-rest-impl/src/main/java/com/liferay/change/tracking/rest/internal/dto/v1_0/converter/CTEntryDTOConverter.java
> +		}
Use if and else-if so that when the if evaluates to true, the rest if checks can be skipped.

2024-09-05 22:45 UTC, pei-jung commented
@ctang3 can you close https://github.com/liferay-site-management/liferay-portal/pull/1346 and have all the commits in one PR so that we can send them together?

2024-09-09 17:31 UTC, ctang3 commented
ci:test:publications

2024-09-09 17:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10083/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10083/jenkins-report.html">here</a>.</b></p>

2024-09-09 19:58 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 82 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2aa20937beaf1415ddacba4447d5aee553580e0d">2aa20937beaf1415ddacba4447d5aee553580e0d</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/10083/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10083/jenkins-report.html">here</a>.</b></p>

2024-09-09 21:49 UTC, ctang3 commented
ci:test:publications

2024-09-09 22:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12508/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12508/jenkins-report.html">here</a>.</b></p>

2024-09-10 00:28 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 82 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/26deb1222f184b08a1a6dedf9562429238395d86">26deb1222f184b08a1a6dedf9562429238395d86</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12508/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12508/jenkins-report.html">here</a>.</b></p>

2024-09-10 00:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/12508/">test-portal-acceptance-pullrequest(master)#12508</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/12508/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-site-management/liferay-portal/pull/1372">liferay-site-management#1372</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/6014754">[master] ci:test:publications - ctang3 &gt; liferay-site-management - PR#1372 - 2024-09-09[15:43:23]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>6014754<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/27390/">publish-testray-report#27390</a><br/></div></div>

2024-09-10 07:58 UTC, ctang3 commented
ci:test:publications

2024-09-10 07:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>publications</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10256/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10256/jenkins-report.html">here</a>.</b></p>

2024-09-10 09:47 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 82 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.NullPointerException
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/839e11f2525c8067989ea15f099940d118ea2d2d">839e11f2525c8067989ea15f099940d118ea2d2d</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10256/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10256/jenkins-report.html">here</a>.</b></p>

2024-09-10 09:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10256/">test-portal-acceptance-pullrequest(master)#10256</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10256/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-site-management/liferay-portal/pull/1372">liferay-site-management#1372</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/6369537">[master] ci:test:publications - ctang3 &gt; liferay-site-management - PR#1372 - 2024-09-10[00:58:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>6369537<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/22806/">publish-testray-report#22806</a><br/></div></div>

2024-09-10 18:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/10256/">test-portal-acceptance-pullrequest(master)#10256</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10256/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>publications<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-site-management/liferay-portal/pull/1372">liferay-site-management#1372</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/6369537">[master] ci:test:publications - ctang3 &gt; liferay-site-management - PR#1372 - 2024-09-10[00:58:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>6369537<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/22813/">publish-testray-report#22813</a><br/></div></div>

2024-09-12 03:15 UTC, pei-jung commented
@ctang3 please see my changes in https://github.com/liferay-site-management/liferay-portal/pull/1390. Thanks!

2024-09-12 03:15 UTC, closed without merging